behaviors:
  EscapeAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 2.0e-4
      batch_size: 256
      buffer_size: 1000000
      buffer_init_steps: 2000
      tau: 0.005
      steps_per_update: 1.0
      save_replay_buffer: false
      init_entcoef: 0.1
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 500_000
    time_horizon: 128
    summary_freq: 10000
