behaviors:
  EscapeAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 128
      buffer_size: 500000
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 1.0
      save_replay_buffer: false
      init_entcoef: 0.2
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2.0e5
    time_horizon: 64
    summary_freq: 10000
